name       : iproute2
homepage   : http://www.linuxfoundation.org/collaborate/workgroups/networking/iproute2
version    : 3.19.0
release    : 1
source     :
    - https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-3.19.0.tar.xz : e2f9f8c36e166f2ba6c0e1e7a9ad84cdf7c1615b93df49dac44563d7b57fd7b0
license    : GPL-2.0
summary    : Utilities for controlling TCP / IP networking
description: |
    Iproute2 is a collection of utilities for controlling TCP / IP networking and traffic control in Linux. It is currently maintained by Stephen Hemminger <shemminger@osdl.org>. The original author, Alexey Kuznetsov, is well known for the QoS implementation in the Linux kernel.
    
    Most network configuration manuals still refer to ifconfig and route as the primary network configuration tools, but ifconfig is known to behave inadequately in modern network environments. They should be deprecated, but most distros still include them. Most network configuration systems make use of ifconfig and thus provide a limited feature set. The /etc/net project aims to support most modern network technologies, as it doesn't use ifconfig and allows a system administrator to make use of all iproute2 features, including traffic control.
    s
    iproute2 is usually shipped in a package called iproute or iproute2 and consists of several tools, of which the most important are ip and tc. ip controls IPv4 and IPv6 configuration and tc stands for traffic control. Both tools print detailed usage messages and are accompanied by a set of manpages.
builddeps  :
    - pkgconfig(xtables)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
